# Generated by Django 5.2.5 on 2025-08-29 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_alerta_categoria_dispositivo_medicion_zona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='medicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='dispositivos.medicion'),
        ),
    ]
